# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hour_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
