# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hour_app', '0002_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='restaurant_name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
